version: "3.5"

services:
  db:
    image: postgres:latest
    hostname: db
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=admin
      - POSTGRES_DB=swf
    ports:
      - "5432:5432"
    volumes:
      - ./database:/docker-entrypoint-initdb.d

networks:
  default:
    driver: bridge
    name: swf-nginx-2024q1