spring.application.name: swflab

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOSTNAME:localhost}:5432/swf
    username: admin
    password: 123
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate.ddl-auto: validate
    database: postgresql

swf:
  domain: "test.adolfoeloy.com"
  workflow: "swf-sns-workflow"
  workflow-version: "21e98f23-cd31-4267-b679-efef96d67cc1"
  decision-task-list: "initial-decision-task-list"
  activities:
    - name: "get_contact_activity"
      version: "v1"
    - name: "subscribe_topic_activity"
      version: "v1"
    - name: "wait_for_confirmation_activity"
      version: "v1"
    - name: "send_result_activity"
      version: "v1"
